server:
  port: 8761
eureka:
  instance:
    virtualHostName: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.virtualHostName}:${server.port}/eureka/


